name    'alkivi-bind'
version '0.2.1'
source 'https://github.com/alkivi-sas/puppet-bind'
author 'alkivi'
license 'LGPLv3'
summary 'Controls bind9 server'
description 'Setup bind9 server'
project_page 'https://github.com/alkivi-sas/puppet-bind'
dependency 'puppetlabs/stdlib', '>=3.0.0'
dependency 'puppetlabs/concat', '>=1.0.0'

