name    'alkivi-bind'
version '0.0.1'
source 'https://github.com/alkivi/puppet-bind'
author 'alkivi'
license 'LGPLv3'
summary 'Controls bind9 server'
description 'Setup bind9 server'
project_page 'https://github.com/alkivi/puppet-bind'
dependency 'puppetlabs/stdlib', '>3.x'
